name: Test and Build
on: [push, release]

jobs:
  setup-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Docker compose
        run: docker-compose -f ./docker/docker-compose.yml up -d
      - name: Wait for docker compose
        run: chmod +x ./docker/wait.sh & ./docker/wait.sh postgres
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew check
  release:
    runs-on: ubuntu-latest
    needs: setup-docker
    if: github.event_name == 'release'
    steps:
      - name: Release
        run: ./gradlew build
